In [1]:
import torch

In [14]:
randint = torch.randint(0, 10, (5,))
randint

tensor([6, 5, 9, 7, 2])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [0.3, 0.4]])
tensor

tensor([[0.1000, 1.2000],
        [0.3000, 0.4000]])

In [4]:
zeros = torch.zeros((2, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
import torch.nn as nn
import torch
sample = torch.tensor([10.,10.,10.])
linears = nn.Linear(3,3,bias=True)
print(linears(sample))

tensor([-0.5181, -0.6926,  0.6548], grad_fn=<ViewBackward0>)


weight*x+bias   
weight kí hiệu là W^t
bias là false thì là weight*x
if bias==False and input ==[0,0,0] --> output=[0,0,0]
if bias==True and input==[0,0,0] --> output= giá trị trọng số 
hiện tại trọng số là ngẫu nhiên 

In [6]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0,2.0,3.0])   #tổng là 1

softmax_output = F.softmax(tensor1, dim=0)

softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [7]:
tensor2 = torch.tensor([[1.0, 2.0, 3.0], 
                        [1.0, 1.0, 1.0]])
softmax_output_1 = F.softmax(tensor2, dim=1) #dim=1 thì tổng ngang = 1 dim=0 thì tổng dọc là 1

softmax_output_1

tensor([[0.0900, 0.2447, 0.6652],
        [0.3333, 0.3333, 0.3333]])

công thức
e^i for i in input(tensor)
lấy tổng các số 
lấy e^i chia cho tổng 
/// trong trường hợp nhiều chiều 
nếu dim=0 thì lấy e^i chia cho tổng của cột còn dim=1 thì lấy e^i chia cho tổng của hàng
nếu dim=-1 thì lấy chiều cuối cùng 

In [8]:
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size,embedding_dim)

input = torch.LongTensor([1,5,3,2])

output = embedding(input)

print(output.shape)
output

torch.Size([4, 6])


tensor([[-0.9739,  1.1031,  0.2596,  0.0499,  1.4850,  0.0306],
        [-0.6812, -1.2772,  0.0128, -0.8437, -0.1939,  0.0894],
        [ 2.4368,  0.7895, -0.8373, -0.6774,  1.0171, -1.3045],
        [-0.2125,  0.7918, -0.9195,  1.8069, -0.1631,  0.9672]],
       grad_fn=<EmbeddingBackward0>)

In [9]:
a= torch.tensor([[1,2],[3,4],[5,6]])
b= torch.tensor([[7,8,9],[10,11,12]])

a@b

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [20]:
int_64 = torch.randint(1, (2,3)).float()

float_32 = torch.rand(3,2)

print(int_64.dtype, float_32.dtype)

result = torch.matmul(int_64, float_32)

result

torch.float32 torch.float32


tensor([[0., 0.],
        [0., 0.]])